version: '3'

env:
  CONSOLE: docker compose exec -it shopware ./bin/console

tasks:
  init:
    cmds:
      - task: start
      - $CONSOLE plugin:refresh -s
      - $CONSOLE plugin:install -c -a JChannelpilotExporter

  console:
    cmds:
      - $CONSOLE {{.CLI_ARGS}}

  start:
    cmds:
      - docker compose up -d

  stop:
    cmds:
      - docker compose down

  restart:
    cmds:
      - task: stop
      - task: start

  remove:
    cmds:
      - docker compose down -v

  reset:
    cmds:
      - task: remove
      - task: init

  generate-fake-data:
    cmds:
      -

  export:
    cmds:
      - $CONSOLE j:channel_pilot:export
