version: '3'

env:
  CONSOLE: docker compose exec -it shopware ./bin/console
  COMPOSER: docker compose exec -it shopware composer

tasks:
  init:
    cmds:
      - task: start
      - $COMPOSER install
      - $COMPOSER require --dev fakerphp/faker
      - $CONSOLE plugin:refresh -s
      - $CONSOLE plugin:install -c -a JChannelpilotExporter

  console:
    cmds:
      - $CONSOLE {{.CLI_ARGS}}

  composer:
    cmds:
      - $COMPOSER {{.CLI_ARGS}}

  start:
    cmds:
      - docker compose up -d

  stop:
    cmds:
      - docker compose down

  restart:
    cmds:
      - task: stop
      - task: start

  remove:
    cmds:
      - docker compose down -v

  reset:
    cmds:
      - task: remove
      - task: init

  generate-fake-data:
    cmds:
      - $CONSOLE j:channel_pilot:generate_fake_products

  clean:
    cmds:
      - $CONSOLE cache:clear

  export:
    cmds:
      - $CONSOLE j:channel_pilot:export
